config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new' 
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 100 }
  mount_uploader :image, ImageUploader
  default_scope -> { order(created_at: :desc) }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :blogs
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end
  def new
    @blog = Blog.new
  end

  def create
     @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "done!"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
    if @blog.user == current_user
      render :edit
    else
      redirect_to blogs_path
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "edit completed!"
    else
      render :edit
    end
  end

  def destroy
    if @blog.user == current_user
      @blog.destroy
      redirect_to blogs_path, notice:"deleted!"
    else
      redirect_to blogs_path
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'login faild...'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, notice: "logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new'|| action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <i class="fas fa-leaf fa-lg"></i>
      <%= form.label :title %>
      <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <i class="far fa-comment-dots fa-lg"></i>
      <%= form.label :content %>
      <%= form.text_field :content %>
  </div>
  <%= image_tag @blog.image.url %>
  <br>
  <label>
    <i class="fas fa-image fa-lg"></i>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </label>
  <br>
  <%= button_tag type: "submit", class: "submit-btn", title: "Submit" do %>
    <i class="fas fa-paper-plane fa-lg"></i>
  <% end %>
  |
  <%= link_to blogs_path, title: "back" do %>
    <i class="fas fa-backspace fa-lg"></i>
  <% end %>
<% end %>

app/views/blogs/confirm.html.erb
<div class="container">
<h2>以下の内容で、投稿する。</h2>
<div>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p><i class="fas fa-leaf fa-lg"></i>Title:  <%= @blog.title %></p>
  <p><i class="far fa-comment-dots fa-lg"></i>Content:  <%= @blog.content %></p>

  <%= form.label :image do %>
    <i class="fas fa-image fa-2x"></i>
  <% end %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>
</div>
<br>
  <%= button_tag type: "submit", class: "submit-btn", title: "Submit" do %>
    <i class="fas fa-paper-plane fa-lg"></i>
  <% end %>
  |
  <label>
    <i class="fas fa-undo fa-lg"></i>
    <div class="field">
      <%= form.submit "戻る", name: 'back' %>
    </div>
  </label>
<% end %>
</div>

app/views/blogs/edit.html.erb
<div class="container">
<h2>投稿を編集する</h2>
<%= render 'form' %>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <h2 class="title">投稿一覧</h2>
      <div class="row">
        <% @blogs.each do |blog| %>
          <div class="col-md-12 content">
            <br>
            <div class="pic-container">
              <% if blog.image.url %>
              <%= image_tag blog.image.url, class:"pic" %>
              <% end %>
            </div>
            <br>
              <i class="fas fa-clock fa-lg"></i><%= blog.updated_at.strftime("%Y-%m-%d %H:%M") %>
            <br><br>
              <i class="fas fa-user-alt fa-lg"></i><%= blog.user.name %>
            <br><br>
              <i class="fas fa-leaf fa-lg"></i><%= blog.title %>
            <br><br>
              <i class="far fa-comment-dots fa-lg"></i><%= blog.content %>
            <br><br>
              <%= link_to blog_path(blog.id), title:"more detail" do %>
                <i class="fas fa-info-circle margin fa-lg"></i>
              <% end %>
              <% if blog.user.id == current_user.id %>
                <%= link_to edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' }, title:"edit" do %>
                  <i class="far fa-edit margin fa-lg"></i>
                <% end %>
                <%= link_to blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, title:"delete" do %>
                  <i class="far fa-trash-alt margin fa-lg"></i>
                <% end %>
              <% end %>
            <br>
          </div>
        <% end %>
      </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
<h2>投稿しよう</h2>
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <i class="fas fa-leaf fa-lg"></i>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <i class="far fa-comment-dots fa-lg"></i>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <label>
    <i class="fas fa-image fa-lg"></i>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </label>
  <br><br>
  <%= button_tag type: "submit", class: "submit-btn", title: "Submit" do %>
    <i class="fas fa-paper-plane fa-lg"></i>
  <% end %>
  |
  <%= link_to blogs_path, title:"back to top" do %>
    <i class="fas fa-undo fa-lg"></i>
  <% end %>
<% end %>
</div>

app/views/blogs/show.html.erb
<div class="container">
<h2>投稿詳細</h2>
<p><i class="fas fa-leaf fa-lg"></i>Title: <%= @blog.title %></p>
<p><i class="far fa-comment-dots fa-lg"></i>Content: <%= @blog.content %></p>

<p id="notice"><%= notice %></p>
<p><i class="fas fa-image fa-lg"></i>Image: <%= image_tag @blog.image.url %></p>
<br><br>
<% if @blog.user.id == current_user.id %>
  <%= link_to edit_blog_path(@blog), title:"edit" do %>
    <i class="far fa-edit fa-lg"></i>
  <% end %>|
<% end %>
<%= link_to blogs_path, title:"back to top" do %>
  <i class="fas fa-undo fa-lg"></i>
<% end %>
<% unless @blog.user_id == current_user.id %>
|
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Bootstrap</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><i class="fab fa-facebook fa-2x white"></i>
          </a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if logged_in? %>
            <li><%= link_to new_blog_path, title:"create new blog" do %>
                  <i class="far fa-paper-plane fa-2x white"></i>
                <% end %>
            </li>
            <li><%= link_to user_path(current_user.id), title: "profile" do %>
              <i class="fas fa-user-circle fa-2x white"></i>
              <% end %>
            </li>
            <li><%= link_to session_path(current_user.id), title: "logout", method: :delete do %>
              <i class="fas fa-sign-out-alt fa-2x white"></i>
              <% end %>
            </li>
            <% else %>
            <li><%= link_to new_user_path, title: "signup" do %>
              <i class="fas fa-user-plus fa-2x white"></i>
              <% end %>
            </li>
            <li><%= link_to new_session_path, title: "login" do %>
              <i class="fas fa-door-open fa-2x white"></i>
              <% end %>
            </li>
          </ul>
        </div>
        <% end %>
      </div>
  </nav>
  <div class="flash">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
  </div>
    <%= yield %>
  </body>

  <script>
    $(function(){
      $(".danger, .notice").fadeOut(5000);
    });
  </script>
</html>

app/views/users/new.html.erb
<div class="container">
  <h2>Sign up</h2>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= form_with(model: @user, local: true) do |f| %>
      <i class="fas fa-signature fa-lg"></i>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <i class="fas fa-at fa-lg"></i>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <br>
      <i class="fas fa-key fa-lg"></i>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <br>
      <i class="fas fa-key fa-lg second-key"></i>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <br>
      <br>
      <%= button_tag type: "submit", class: "submit-btn", title: "Submit" do %>
      <i class="fas fa-user-plus fa-2x"></i>
      <% end %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <p><i class="fas fa-user fa-lg"></i>User:  <%= @user.name %></p>
  <p><i class="fas fa-at fa-lg"></i>Email:  <%= @user.email %></p>
  <br>
  <%= link_to blogs_path, title:"go to top" do %>
    <i class="fas fa-comments fa-2x"></i>
  <% end %>
</div>